name: .NET

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: PowerMate

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Initialize test reporting
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}

    - name: Restore
      run: dotnet restore --verbosity normal

    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal

    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --settings Tests/Tests.runsettings --logger "trx;LogFileName=TestResults.xml"
        Out-File -InputObject "TEST_EXIT_CODE=$LASTEXITCODE" -FilePath $env:GITHUB_ENV -Append -Encoding UTF8 
        Copy-Item Tests/TestResults/*/coverage.info Tests/TestResults -ErrorAction Continue
        exit 0

    - name: Upload test report
      run: testspace Tests/TestResults/TestResults.xml

    - name: Upload coverage report
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: Tests/TestResults/coverage.info
        format: lcov

    - name: Stop if tests failed
      run: exit $env:TEST_EXIT_CODE

    - name: Pack
      run: dotnet pack ${{ env.ProjectName }} --no-build --configuration Release --verbosity normal

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}.nupkg
        path: ${{ env.ProjectName }}/bin/Release/*.*nupkg
        if-no-files-found: error

    - name: Publish demos
      run: |
        dotnet publish PowerMateVolume -c Release --self-contained false -p:PublishSingleFile=true -r win-x64
        dotnet publish Demo -c Release --self-contained false -p:PublishSingleFile=true -r win-x64
        dotnet publish Demo -c Release --self-contained false -p:PublishSingleFile=true -r win-arm64
        dotnet publish Demo -c Release --self-contained false -p:PublishSingleFile=true -r osx-x64
        dotnet publish Demo -c Release --self-contained false -p:PublishSingleFile=true -r osx-arm64

        New-Item -Name Demo/bin/Release/upload/Windows -Type Directory -ErrorAction SilentlyContinue
        New-Item -Name Demo/bin/Release/upload/MacOS -Type Directory -ErrorAction SilentlyContinue

        Copy-Item PowerMateVolume/bin/Release/net8.0-windows/win-x64/publish/PowerMateVolume.exe Demo/bin/Release/upload/Windows/PowerMateVolume.exe
        Copy-Item Demo/bin/Release/net8.0/win-x64/publish/Demo.exe Demo/bin/Release/upload/Windows/Demo-x64.exe
        Copy-Item Demo/bin/Release/net8.0/win-arm64/publish/Demo.exe Demo/bin/Release/upload/Windows/Demo-ARM64.exe
        Copy-Item Demo/bin/Release/net8.0/osx-x64/publish/Demo Demo/bin/Release/upload/MacOS/Demo-x64
        Copy-Item Demo/bin/Release/net8.0/osx-arm64/publish/Demo Demo/bin/Release/upload/MacOS/Demo-ARM64

    - name: Upload demos
      uses: actions/upload-artifact@v4
      with:
        name: Demos
        path: Demo/bin/Release/upload/
        if-no-files-found: error